# Generated by Django 5.2.1 on 2025-06-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_phone'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='profile', related_query_name='submit_vacansies', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', related_query_name='vacancies', to='user.profile'),
        ),
    ]
