# Generated by Django 5.2.1 on 2025-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Роль пользователя'),
        ),
    ]
